'use client';
import React, { ReactNode, useEffect, useState } from "react";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout, Typography, Button, Alert, Card } from 'antd';
import AppHeader from "../components/AppHeader";
import AppSlideMenu from "../components/AppSlideMenu";
// import Sider from "antd/es/layout/Sider";
// import { Content } from "antd/es/layout/layout";
import Cookies from 'js-cookie';
import { useRouter, usePathname } from 'next/navigation';
import { startTokenExpiryCheck } from '../util/tokenUtils';

const inter = Inter({ subsets: ["latin"] });
const { Content, Sider } = Layout;
const { Title, Paragraph } = Typography;

// export const metadata: Metadata = {
//   title: "huahua Next App",
//   description: "Generated by create next app",
// };

type Role = "admin" | "user" | "guest";

const fetchRole = (): Role => {
  const role = Cookies.get('Role');
  return role as Role || "guest"; // 默认角色为 guest
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const pathname = usePathname();
  const [role, setRole] = useState<Role>("guest");

  useEffect(() => {
    setRole(fetchRole());
    startTokenExpiryCheck(); // 启动JWT过期检查
  }, []);

  const renderContent = () => {
    if (pathname === '/login' || pathname === '/register') {
      return children; // 登录和注册页面直接渲染
    }

    switch (role) {
      case "admin":
      case "user":
        return children;
      default:
        return (
          <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' }}>
            <div style={{ maxWidth: '450px', textAlign: 'center' }}>
              <Alert
                message="请登录后查看更多内容"
                description="您当前处于游客状态，请登录后查看更多内容或进行注册。"
                type="info"
                showIcon
                style={{ marginBottom: '16px' }}
              />
              <Card title="网站特性" style={{ width: '100%' }}>
                <Paragraph style={{ fontSize: '16px', lineHeight: '1.6' }}>
                  我们的网站提供高品质的学生竞赛管理服务，涵盖各类学科竞赛，为您提供全面的报名管理和参赛信息发布功能。
                  用户可以轻松查看和管理自己的报名记录，了解竞赛的最新动态，参与各类精彩比赛，展示自己的才能。
                  竭诚欢迎您加入我们的社区，一同探索和分享学术和技术的乐趣！
                </Paragraph>
                <Button type="primary" style={{ marginTop: '16px' }} onClick={() => router.push('/login')}>登录</Button>
                <Button style={{ marginLeft: '16px' }} onClick={() => router.push('/register')}>注册</Button>
              </Card>
            </div>
          </div>
        );
    }
  };

  return (
    <html lang="en">
      <body className={inter.className}>
      <AntdRegistry>
       <Layout>
        <AppHeader />

        <Layout hasSider>
          <Sider width={200} style={{  backgroundColor:"white", border:'1px #f1f1f1 solid',position:'fixed', left: 0, top: "64px", bottom: 0, overflow: 'auto', padding: 24, }}>
            <AppSlideMenu role={role} />
         </Sider>
         
         <Layout style={{marginLeft: 200}}>
          <Content style={{
              padding: '16px',
              margin: 0,
              minHeight: 'calc(100vh - 64px)',
            
            }}>{renderContent()}</Content>
         </Layout>
        </Layout>        
       
       </Layout>
      </AntdRegistry>
      </body>
    </html>
  );
}
